export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  DASHBOARD: "Dashboard",
  DONOR_NATIONALITY: "DonorNationality",
  DONOR_PHONE: "DonorPhone",
  DONOR_DETAILS: "DonorDetails",
  SELECT_DONATION: "SelectDonation",
  COLLECTION_MODE: "CollectionMode",
  BANK_DEPOSIT: "BankDeposit",
  REPORT: "Report",
  BANK_DEPOSIT_REPORT: "BankDepositReport",
  COLLECTION_REPORT: "CollectionReport",
  CASH_DEPOSIT_DETAILS: "CashDepositDetails",
  CHEQUE_DEPOSIT_DETAILS: "ChequeDepositDetails",
  LOGIN: "Login",
  MESSAGES: "Messages",
  OTP: "OTP",
  REGISTER: "Register",
});
